// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package hu.inf.unideb.proto;

public final class ProtoUser {
  private ProtoUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string rank = 1;</code>
     */
    boolean hasRank();
    /**
     * <code>required string rank = 1;</code>
     */
    java.lang.String getRank();
    /**
     * <code>required string rank = 1;</code>
     */
    com.google.protobuf.ByteString
        getRankBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated string authorites = 3;</code>
     */
    java.util.List<java.lang.String>
        getAuthoritesList();
    /**
     * <code>repeated string authorites = 3;</code>
     */
    int getAuthoritesCount();
    /**
     * <code>repeated string authorites = 3;</code>
     */
    java.lang.String getAuthorites(int index);
    /**
     * <code>repeated string authorites = 3;</code>
     */
    com.google.protobuf.ByteString
        getAuthoritesBytes(int index);

    /**
     * <code>optional bytes image = 4;</code>
     */
    boolean hasImage();
    /**
     * <code>optional bytes image = 4;</code>
     */
    com.google.protobuf.ByteString getImage();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      rank_ = "";
      name_ = "";
      authorites_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      image_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              rank_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                authorites_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              authorites_.add(bs);
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              image_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          authorites_ = authorites_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.inf.unideb.proto.ProtoUser.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.inf.unideb.proto.ProtoUser.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.inf.unideb.proto.ProtoUser.User.class, hu.inf.unideb.proto.ProtoUser.User.Builder.class);
    }

    private int bitField0_;
    public static final int RANK_FIELD_NUMBER = 1;
    private volatile java.lang.Object rank_;
    /**
     * <code>required string rank = 1;</code>
     */
    public boolean hasRank() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string rank = 1;</code>
     */
    public java.lang.String getRank() {
      java.lang.Object ref = rank_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rank_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rank = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRankBytes() {
      java.lang.Object ref = rank_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORITES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList authorites_;
    /**
     * <code>repeated string authorites = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAuthoritesList() {
      return authorites_;
    }
    /**
     * <code>repeated string authorites = 3;</code>
     */
    public int getAuthoritesCount() {
      return authorites_.size();
    }
    /**
     * <code>repeated string authorites = 3;</code>
     */
    public java.lang.String getAuthorites(int index) {
      return authorites_.get(index);
    }
    /**
     * <code>repeated string authorites = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAuthoritesBytes(int index) {
      return authorites_.getByteString(index);
    }

    public static final int IMAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString image_;
    /**
     * <code>optional bytes image = 4;</code>
     */
    public boolean hasImage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes image = 4;</code>
     */
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rank_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < authorites_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, authorites_.getRaw(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, image_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rank_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < authorites_.size(); i++) {
          dataSize += computeStringSizeNoTag(authorites_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAuthoritesList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, image_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof hu.inf.unideb.proto.ProtoUser.User)) {
        return super.equals(obj);
      }
      hu.inf.unideb.proto.ProtoUser.User other = (hu.inf.unideb.proto.ProtoUser.User) obj;

      boolean result = true;
      result = result && (hasRank() == other.hasRank());
      if (hasRank()) {
        result = result && getRank()
            .equals(other.getRank());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && getAuthoritesList()
          .equals(other.getAuthoritesList());
      result = result && (hasImage() == other.hasImage());
      if (hasImage()) {
        result = result && getImage()
            .equals(other.getImage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRank()) {
        hash = (37 * hash) + RANK_FIELD_NUMBER;
        hash = (53 * hash) + getRank().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (getAuthoritesCount() > 0) {
        hash = (37 * hash) + AUTHORITES_FIELD_NUMBER;
        hash = (53 * hash) + getAuthoritesList().hashCode();
      }
      if (hasImage()) {
        hash = (37 * hash) + IMAGE_FIELD_NUMBER;
        hash = (53 * hash) + getImage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static hu.inf.unideb.proto.ProtoUser.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hu.inf.unideb.proto.ProtoUser.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        hu.inf.unideb.proto.ProtoUser.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.inf.unideb.proto.ProtoUser.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.inf.unideb.proto.ProtoUser.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.inf.unideb.proto.ProtoUser.User.class, hu.inf.unideb.proto.ProtoUser.User.Builder.class);
      }

      // Construct using hu.inf.unideb.proto.ProtoUser.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rank_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        authorites_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        image_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hu.inf.unideb.proto.ProtoUser.internal_static_User_descriptor;
      }

      public hu.inf.unideb.proto.ProtoUser.User getDefaultInstanceForType() {
        return hu.inf.unideb.proto.ProtoUser.User.getDefaultInstance();
      }

      public hu.inf.unideb.proto.ProtoUser.User build() {
        hu.inf.unideb.proto.ProtoUser.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hu.inf.unideb.proto.ProtoUser.User buildPartial() {
        hu.inf.unideb.proto.ProtoUser.User result = new hu.inf.unideb.proto.ProtoUser.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rank_ = rank_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          authorites_ = authorites_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.authorites_ = authorites_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.image_ = image_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hu.inf.unideb.proto.ProtoUser.User) {
          return mergeFrom((hu.inf.unideb.proto.ProtoUser.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hu.inf.unideb.proto.ProtoUser.User other) {
        if (other == hu.inf.unideb.proto.ProtoUser.User.getDefaultInstance()) return this;
        if (other.hasRank()) {
          bitField0_ |= 0x00000001;
          rank_ = other.rank_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (!other.authorites_.isEmpty()) {
          if (authorites_.isEmpty()) {
            authorites_ = other.authorites_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAuthoritesIsMutable();
            authorites_.addAll(other.authorites_);
          }
          onChanged();
        }
        if (other.hasImage()) {
          setImage(other.getImage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRank()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hu.inf.unideb.proto.ProtoUser.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hu.inf.unideb.proto.ProtoUser.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object rank_ = "";
      /**
       * <code>required string rank = 1;</code>
       */
      public boolean hasRank() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string rank = 1;</code>
       */
      public java.lang.String getRank() {
        java.lang.Object ref = rank_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rank_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rank = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRankBytes() {
        java.lang.Object ref = rank_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rank_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rank = 1;</code>
       */
      public Builder setRank(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rank = 1;</code>
       */
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rank_ = getDefaultInstance().getRank();
        onChanged();
        return this;
      }
      /**
       * <code>required string rank = 1;</code>
       */
      public Builder setRankBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rank_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList authorites_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAuthoritesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          authorites_ = new com.google.protobuf.LazyStringArrayList(authorites_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAuthoritesList() {
        return authorites_.getUnmodifiableView();
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public int getAuthoritesCount() {
        return authorites_.size();
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public java.lang.String getAuthorites(int index) {
        return authorites_.get(index);
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAuthoritesBytes(int index) {
        return authorites_.getByteString(index);
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public Builder setAuthorites(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthoritesIsMutable();
        authorites_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public Builder addAuthorites(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthoritesIsMutable();
        authorites_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public Builder addAllAuthorites(
          java.lang.Iterable<java.lang.String> values) {
        ensureAuthoritesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, authorites_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public Builder clearAuthorites() {
        authorites_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authorites = 3;</code>
       */
      public Builder addAuthoritesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthoritesIsMutable();
        authorites_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes image = 4;</code>
       */
      public boolean hasImage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes image = 4;</code>
       */
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      /**
       * <code>optional bytes image = 4;</code>
       */
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes image = 4;</code>
       */
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final hu.inf.unideb.proto.ProtoUser.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hu.inf.unideb.proto.ProtoUser.User();
    }

    public static hu.inf.unideb.proto.ProtoUser.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public hu.inf.unideb.proto.ProtoUser.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"E\n\004User\022\014\n\004rank\030\001 \002(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022\022\n\nauthorites\030\003 \003(\t\022\r\n\005image\030\004 " +
      "\001(\014B \n\023hu.inf.unideb.protoB\tProtoUser"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Rank", "Name", "Authorites", "Image", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
